---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
- name: Set some hostvars
  ansible.builtin.import_playbook: ../../common/converge-version.yml
  vars:
    _cifmw_update_test_version: "v1.0.7"

# ^^^ This must created the correct /home/zuul/src/github.com/openstack-k8s-operators/architecture/examples/common/olm-subscriptions/kustomization.yaml



# the ci_gen_kustomize_values creates:
# /home/zuul/ci-framework-data/artifacts/ci_gen_kustomize_values/olm-values/values.yaml
# using
# /home/zuul/ci-framework-data/artifacts/ci_k8s_snippets/olm-values/02_ci_data.yaml
# from the olm/values.yaml.j2 file.
# The the value file is copied over /home/zuul/src/github.com/openstack-k8s-operators/architecture/examples/common/olm-subscriptions/values.yaml
# and kustomize is run.

# - name: Converge
#   hosts: all
#   vars:
# #    cifwm_update_deploy_old_version: true
#     cifw_update_deployment_version: \"v1.0.3\"
#     cifmw_ci_gen_kustomize_values_architecture_repo: >-
#       {{
#       cifmw_architecture_repo |
#       default([
#       ansible_user_dir,
#       "src',
#       'github.com',
#       'openstack-k8s-operators',
#       'architecture'] | path_join)
#       }}
#     cifmw_architecture_scenario: foobar
#     pre_deploy:
#         - name: 90 Install old operator
#           type: playbook
#           source: "{{ ci_framework_base_src_dir }}/hooks/playbooks/operator_install_old_version.yml"
# 
# 
#   vars_files:
#     - ../../defaults/main.yml
#     - ./resources/vars.yml
#   tasks:
#     - name: Deploy OSP operators
#       ansible.builtin.import_role:
#         name: kustomize_deploy
#         tasks_from: install_operators.yml
# 
# 
