---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Prepare OpenShift CRC
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if CRC VM exists
      command: "virsh list --all --name | grep '^crc$'"
      register: vm_exists
      failed_when: false
      changed_when: false
      become: true

    - name: Debug VM existence
      debug:
        var: vm_exists.stdout

    - name: deploy CRC
      vars:
        cifmw_manage_secrets_pullsecret_file: "{{ lookup('env', 'HOME') }}/pull-secret.txt"
        cifmw_rhol_crc_config:
          disk-size: 150
          memory: 65536
      ansible.builtin.include_role:
        name: "rhol_crc"
      when: vm_exists.stdout == ""

    - name: Create a snapshot after initial setup
      command: "virsh snapshot-create-as --domain crc --name initial-setup --description 'Initial setup snapshot' --disk-only --atomic"
      become: true
      when: vm_exists.stdout == ""
